name: checks

on:
  push:
    branches: ['main']
  pull_request:
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm i
      - run: deno task test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm i
      - run: npm exec playwright install --with-deps
      - run: deno task build
      - run: npm run e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm i
      - run: deno lint && deno fmt --check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm i
      - run: deno task build
  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm i
      - run: deno task performance:check
