name: google

on:
  deployment_status:

jobs:
  update-sitemap:
    name: update sitemap
    runs-on: ubuntu-latest
    if:
      github.event.deployment_status.state == 'success' &&
      github.event.deployment.environment == 'production'
    steps:
      - name: update sitemap
        run: |
          curl -f -X GET "http://www.google.com/ping?sitemap=https%3A%2F%2Fwww.r%C3%B6ssing.de%2Fsitemap.xml"
